### ISSUE TITLE
Builtin year constant

### ISSUE THREAD

**Issue by sagikazarmark** [denis-tingajkin/go-header#5]
Add a builtin constant for the current year. It would also be nice, if go header could validate headers that contain previous years, since they don't have to be updated.

**Comment by denis-tingajkin** [comment]
> It would also be nice, if go header could validate headers that contain previous years, since they don't have to be updated.

Actually, it is a problem only if go-header using under golangci-linter. Directly can be used something like `go-header $(git diff --name-only)`

Also, I think this case should work fine if golangci linter has an option `-new`, but if golangci linter works with the full project then it is a problem :) 

I'll try to discuss this problem with golangci-team.

**Comment by sagikazarmark** [comment]
I think it makes sense to support old files as well. For example, if the template changes, I'd expect old files to be updated as well, so I should be able to lint everything, too.

**Comment by denis-tingajkin** [comment]
Should be fixed in golangci v1.34.0.

**Comment by denis-tingajkin** [comment]
Closing this. Let me know if something still not working as expected :)
